### ISSUE TITLE
Multi machine hadoop setup

### ISSUE THREAD

**Issue by yuvalye** [sudar/Yahoo_LDA#2]
I have an hadoop distribution running locally. 
I followed the multi machine setup in the distribution,and uploaded LDALibs.jar to the HDFS and also put there a ut_out folder. 
When running the script - 
./runLDA.sh 1 "" train default ./ut_out/ydir_1k.txt ./ld 8000 25 500 hdfs://localhost:9000/.../LDALibs.jar 1 I 
it fails. 
This is the output I get: 
- /hadoop/bin/hadoop jar /hadoop/hadoop-streaming.jar -Dmapred.job.queue.name=default -Dmapred.reduce.tasks.speculative.execution=false -Dmapred.job.reduce.memory.mb=8000 -Dmapred.reduce.tasks=1 -Dmapred.child.ulimit=8001000 -Dmapred.task.timeout=1800000 -Dmapred.reduce.max.attempts=1 -Dmapreduce.job.acl-view-job=shravanm,smola -input ./ut_out/ydir_1k.txt -output ./ld_0 -cacheArchive hdfs://1..../LDALibs.jar#LDALibs -mapper /bin/cat -reducer 'Formatter.sh 1 " " ' -file Formatter.sh -file functions.sh -numReduceTasks 1
  11/07/27 14:47:56 WARN streaming.StreamJob: -cacheArchive option is deprecated, please use -archives instead.
  packageJobJar: [Formatter.sh, functions.sh, /tmp/hadoop-datastore/hadoop/hadoop-unjar1697472003615487337/] [] /tmp/streamjob6284543710483930588.jar tmpDir=null
  11/07/27 14:47:57 INFO mapred.FileInputFormat: Total input paths to process : 1
  11/07/27 14:47:57 INFO streaming.StreamJob: getLocalDirs(): [/tmp/hadoop-datastore/hadoop/mapred/local]
  11/07/27 14:47:57 INFO streaming.StreamJob: Running job: job_201107240937_0039
  11/07/27 14:47:57 INFO streaming.StreamJob: To kill this job, run:
  11/07/27 14:47:57 INFO streaming.StreamJob: /hadoop/bin/../bin/hadoop job  -Dmapred.job.tracker=10.149.19.120:9001 -kill job_201107240937_0039
  11/07/27 14:47:57 INFO streaming.StreamJob: Tracking URL: http://ip:50030/jobdetails.jsp?jobid=job_201107240937_0039
  11/07/27 14:47:58 INFO streaming.StreamJob:  map 0%  reduce 0%
  11/07/27 14:48:05 INFO streaming.StreamJob:  map 100%  reduce 0%
  11/07/27 14:48:14 INFO streaming.StreamJob:  map 100%  reduce 33%
  11/07/27 14:48:17 INFO streaming.StreamJob:  map 100%  reduce 0%
  11/07/27 14:48:20 INFO streaming.StreamJob:  map 100%  reduce 100%
  11/07/27 14:48:20 INFO streaming.StreamJob: To kill this job, run:
  11/07/27 14:48:20 INFO streaming.StreamJob: /home/snoop/hadoop/hadoop/bin/../bin/hadoop job  -Dmapred.job.tracker=ip:9001 -kill job_201107240937_0039
  11/07/27 14:48:20 INFO streaming.StreamJob: Tracking URL: http://ip:50030/jobdetails.jsp?jobid=job_201107240937_0039
  11/07/27 14:48:20 ERROR streaming.StreamJob: Job not Successful!
  11/07/27 14:48:20 INFO streaming.StreamJob: killJob...
  Streaming Job Failed!
- exit_code=1
- set +x
  Unable to run Formatter on your corpus

and the error log for the task that fails is:

model=1 flags=" " trained_data=""
/tmp/hadoop-datastore/hadoop/mapred/local/taskTracker/jobcache/job_201107240937_0039/attempt_201107240937_0039_r_000000_0/work/./Formatter.sh: line 31: /tmp/hadoop-datastore/hadoop/mapred/local/taskTracker/jobcache/job_201107240937_0039/attempt_201107240937_0039_r_000000_0/work/LDALibs/formatter: Permission denied
Formatter returned an error code of 126
java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 126
    at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:311)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:545)
    at org.apache.hadoop.streaming.PipeReducer.close(PipeReducer.java:137)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:473)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:411)
    at org.apache.hadoop.mapred.Child.main(Child.java:170)
log4j:WARN No appenders could be found for logger (org.apache.hadoop.hdfs.DFSClient).
log4j:WARN Please initialize the log4j system properly.

Any ideas/thoughs what wrong? 
Thanks
Yuval

**Comment by KushalDave** [comment]
Yuval,

JAR by default does not remember the permissions of the files inside the jar.
I worked around this problem by changing the permissions of the directory after it is un-jarred .. in Formatter.sh
here is the change in code ..

#!/bin/sh

. ./functions.sh

#Main starts
synch_dir=${mapred_output_dir}"/temporary/synchronize";
hostnames_dir=${mapred_output_dir}"/temporary/hostnames";
model=$1;
flags=$2;

echo "model=$model flags=\"$flags\"" 1>&2;

JHOME=`pwd`;
LDALIBS=$JHOME"/LDALibs";
chmod 777 -R $LDALIBS
export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:$LDALIBS/lib;
PORT=25342;
JAVA="/home/hdev/jdk1.6.0_21/bin/java";

mkdir -p $JHOME/out;
cd $JHOME/out;
cp $LDALIBS/Tokenizer.class .;

if [ $model -eq 1 ]; then
  $JAVA Tokenizer | $LDALIBS/formatter --model=$model
else
  $LDALIBS/formatter --model=$model
fi;
check_exit_status $? "Formatter";
/home/hdev/hadoop-0.20.2/bin/hadoop dfs -touchz ${mapred_output_dir}/input/${mapred_task_partition};
cd $JHOME
`/home/hdev/hadoop-0.20.2/bin/hadoop dfs -put out ${mapred_output_dir}/${mapred_task_partition}`;

Hope it helps.

**Comment by KushalDave** [comment]
Notice the inserted line chmod 777 -R $LDALIBS ...

**Comment by shravanmn** [comment]
I think the umask on the executing machine is not set properly. Try and set it to 022 and check if the problem exists.
