### ISSUE TITLE
unable to run formatter

### ISSUE THREAD

**Issue by josephykwang** [sudar/Yahoo_LDA#6]
I run

./runLDA.sh 1 "data" train default "/user/jwang/simulation/data/offers/current" "/user/jwang/workspace/lda/" 3244 1000 5 /user/jwang/software/YLDA/LDALibs.jar 20 "/user/jwang/workspace/ldatemp"

There are text files in /user/jwang/simulation/data/offers/current, where each line is a document.

It invoked a streaming job, where mapper run successfully. However, the reducers failed. Here is the error associated with one of reducers:

java.io.IOException: subprocess exited with error code 1
R/W/S=540/0/0 in:77=540/7 [rec/s] out:0=0/7 [rec/s]
minRecWrittenToEnableSkip_=9223372036854775807 LOGNAME=null
HOST=null
USER=root
HADOOP_USER=null
last Hadoop input: |null|
last tool output: |null|
Date: Thu Jan 05 16:04:36 PST 2012
Broken pipe
    at org.apache.hadoop.streaming.PipeReducer.reduce(PipeReducer.java:131)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:469)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:417)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
    at org.apache.hadoop.mapred.Child.main(Child.java:264)

Any idea?

**Comment by josephykwang** [comment]
Looking at the failed reducer, it has 

stderr logs

model=1 flags=" " trained_data=""
Could not create the Java virtual machine.
W0105 16:23:32.911026 13315 Controller.cpp:115] ----------------------------------------------------------------------
W0105 16:23:32.911649 13315 Controller.cpp:117] Log files are being stored at /data/2/mr/local/taskTracker/jwang/jobcache/job_201112201444_4258/attempt_201112201444_4258_r_000000_0/work/out/formatter.*
W0105 16:23:32.911669 13315 Controller.cpp:119] ----------------------------------------------------------------------
W0105 16:23:32.911890 13315 Controller.cpp:126] Assuming that corpus is being piped through stdin. Reading from stdin...
W0105 16:23:32.912675 13315 Controller.cpp:143] Formatting Complete. Formatted document stored in lda.wor. You have used lda as the output prefix. Make sure you use the same as the input prefix for learnTopics
W0105 16:23:32.912698 13315 Controller.cpp:149] Dumping dictionary for later use by learnTopics into lda.dict.dump
W0105 16:23:32.912806 13315 Controller.cpp:153] Finished dictionary dump
W0105 16:23:32.912832 13315 Controller.cpp:154] Formatting done
W0105 16:23:32.912848 13315 Controller.cpp:158] Total number of unique words found: 6
W0105 16:23:32.912865 13315 Controller.cpp:159] Total num of docs found: 2
W0105 16:23:32.912883 13315 Controller.cpp:160] Total num of tokens found: 6
Formatter done

**Comment by josephykwang** [comment]
2012-01-06 06:28:16,483 INFO org.apache.hadoop.streaming.PipeMapRed: mapRedFinished
2012-01-06 06:28:16,499 WARN org.apache.hadoop.streaming.PipeMapRed: java.io.IOException: Bad file descriptor
    at java.io.FileOutputStream.writeBytes(Native Method)
    at java.io.FileOutputStream.write(FileOutputStream.java:260)
    at java.io.BufferedOutputStream.write(BufferedOutputStream.java:105)
    at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:65)
    at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:123)
    at java.io.DataOutputStream.flush(DataOutputStream.java:106)
    at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:569)
    at org.apache.hadoop.streaming.PipeReducer.close(PipeReducer.java:137)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:484)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:417)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
    at org.apache.hadoop.mapred.Child.main(Child.java:264)

2012-01-06 06:28:16,499 INFO org.apache.hadoop.streaming.PipeMapRed: mapRedFinished
2012-01-06 06:28:16,509 INFO org.apache.hadoop.mapred.TaskLogsTruncater: Initializing logs' truncater with mapRetainSize=-1 and reduceRetainSize=-1
2012-01-06 06:28:16,514 WARN org.apache.hadoop.mapred.Child: Error running child
java.io.IOException: subprocess still running
R/W/S=524/0/0 in:58=524/9 [rec/s] out:0=0/9 [rec/s]
minRecWrittenToEnableSkip_=9223372036854775807 LOGNAME=null
HOST=null
USER=root
HADOOP_USER=null
last Hadoop input: |null|
last tool output: |null|
Date: Fri Jan 06 06:28:16 PST 2012
Broken pipe
    at org.apache.hadoop.streaming.PipeReducer.reduce(PipeReducer.java:131)
    at org.apache.hadoop.mapred.ReduceTask.runOldReducer(ReduceTask.java:469)
    at org.apache.hadoop.mapred.ReduceTask.run(ReduceTask.java:417)
    at org.apache.hadoop.mapred.Child$4.run(Child.java:270)
    at java.security.AccessController.doPrivileged(Native Method)
    at javax.security.auth.Subject.doAs(Subject.java:396)
    at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1127)
    at org.apache.hadoop.mapred.Child.main(Child.java:264)
2012-01-06 06:28:16,520 INFO org.apache.hadoop.mapred.Task: Runnning cleanup for the task

**Comment by josephykwang** [comment]
identity: `DM_Server_1'
facet: 
operation: ice_isA
terminate called after throwing an instance of 'IceUtil::Exception'
  what():  Outgoing.cpp:424: IceUtil::Exception
**\* Aborted at 1325881407 (unix time) try "date -d @1325881407" if you are using GNU date ***
PC: @       0x3fd2e30265 (unknown)
**\* SIGABRT (@0xc3b80000232f) received by PID 9007 (TID 0x2b76ec09f8e0) from PID 9007; stack trace: ***
    @       0x3fd360eb10 (unknown)
    @       0x3fd2e30265 (unknown)
    @       0x3fd2e31d10 (unknown)
    @     0x2b76ebe5ad14 (unknown)
    @     0x2b76ebe58e16 (unknown)
    @     0x2b76ebe58e43 (unknown)
    @     0x2b76ebe58f2a (unknown)
    @           0x43fa4e DM_Client::add_server()
    @           0x4403de DM_Client::DM_Client()
    @           0x49da45 Unigram_Model_Synchronizer_Helper::Unigram_Model_Synchronizer_Helper()
    @           0x49d465 Unigram_Model_Synchronized_Training_Builder::create_execution_strategy()
    @           0x447cb4 Model_Director::build_model()
    @           0x43965b main
    @       0x3fd2e1d994 (unknown)
    @           0x40d879 (unknown)

**Comment by shravanmn** [comment]
What are you trying to run?

Training mode or testing mode?
Also what is the second argument "data" ? The second argument is meant 
to be parameters to the learntopics program if any. learntopics does not 
take any argument called data.

--Shravan

**Comment by josephykwang** [comment]
I'm trying to run training. For formatter issue, I think it is related to give output directory with / at the end. If I changed
to /user/jwang/workspace/lda, then the formatter run w/o any problem.

However, I'm running into other issues when trying to run training using Hadoop. Get exception in DM_server:add_server
call. To work around, I simply add a catch-all around add_server call. However, it then failed at the very end when
trying to save global file. I'd opened other issues for these. Any suggestion on how I can work around these issues?

thanks for looking into these,

Joseph Wang

**Comment by shravanmn** [comment]
If you are running training why are you passing the training-output 
folder? This has to be used only in test mode. Remove all your changes 
and run the following command:

./runLDA.sh 1 train default "/user/jwang/simulation/data/offers/current" "/user/jwang/workspace/lda/" 3244 1000 5 /user/jwang/software/YLDA/LDALibs.jar 20

I hope your documents are in the right format.

--Shravan

**Comment by josephykwang** [comment]
Sorry, forgot to update the ticket. I run the following command.

./runLDA.sh 1 "" train default "/user/jwang/simulation/data/offers/currentlda" "/user/jwang/workspace/lda" 6144 1000 10 /user/jwang/software/LDALibs.jar 20

Each line has 

<documentid><space><documentid><space><document text>

**Comment by josephykwang** [comment]
Note that I'd run github version as well.

**Comment by josephykwang** [comment]
Below is a mapper of output for 

./runLDA.sh 1 "" train default "/user/jwang/simulation/data/offers/currentlda" "/user/jwang/workspace/lda" 3244 1000 10 /user/jwang/software/YLDA/LDALibs.jar 20
, which showed there is an exception in add_server.

supergroup         10 2012-01-09 07:05 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/10
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/11
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/13
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/15
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/16
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:05 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/19
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/2
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/3
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/4
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/6
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/7
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:04 /user/jwang/workspace/ldanew/temporary/synchronize/clid_names/8
Num of clients done:  12
Sleeping
Num of clients done:  20
All clients done!
Servers Param:  10.101.173.139:25342,10.101.173.139:25342,10.101.173.139:25342,10.101.173.139:25342,10.101.173.117:25342,10.101.173.117:25342,10.101.173.117:25342,10.101.173.117:25342,10.101.173.144:25342,10.101.173.146:25342,10.101.173.133:25342,10.101.173.146:25342,10.101.173.133:25342,10.101.173.146:25342,10.101.173.151:25342,10.101.173.144:25342,10.101.173.151:25342,10.101.173.133:25342,10.101.173.151:25342,10.101.173.146:25342
Synch directory:  hdfs://hadooprsonn001.bo1.shopzilla.sea/user/jwang/workspace/ldanew/temporary/synchronize/ice
Attaching DM_Server_Adapter to endpoint default -h 10.101.173.139 -p 25342
Network.cpp:1104: Ice::SocketException:
socket exception: Address already in use
Num of map tasks:  20
Found 12 items
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/0
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/1
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/11
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/13
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/15
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:05 /user/jwang/workspace/ldanew/temporary/synchronize/ice/18
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/2
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/3
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/4
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/6
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/7
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:06 /user/jwang/workspace/ldanew/temporary/synchronize/ice/8
Num of clients done:  12
Sleeping
Num of clients done:  20
All clients done!
W0109 07:07:13.074528 29329 Controller.cpp:96] ----------------------------------------------------------------------
W0109 07:07:13.075181 29329 Controller.cpp:98] Log files are being stored at /data/2/mr/local/taskTracker/jwang/jobcache/job_201201082150_0047/attempt_201201082150_0047_m_000002_0/work/out/learnTopics.*
W0109 07:07:13.075202 29329 Controller.cpp:100] ----------------------------------------------------------------------
W0109 07:07:13.075518 29329 Controller.cpp:115] You have chosen multi machine training mode
W0109 07:07:13.075800 29329 Unigram_Model_Training_Builder.cpp:60] Initializing Dictionary from lda.dict.dump
W0109 07:07:14.276371 29329 Unigram_Model_Training_Builder.cpp:62] Dictionary Initialized
W0109 07:08:04.555203 29329 Unigram_Model_Trainer.cpp:49] Initializing Word-Topic counts table from docs lda.wor, lda.top using 500259 words & 1000 topics.
W0109 07:09:19.218955 29329 Unigram_Model_Trainer.cpp:53] Initialized Word-Topic counts table
W0109 07:09:19.219081 29329 Unigram_Model_Trainer.cpp:57] Initializing Alpha vector from Alpha_bar = 50
W0109 07:09:19.219159 29329 Unigram_Model_Trainer.cpp:60] Alpha vector initialized
W0109 07:09:19.219182 29329 Unigram_Model_Trainer.cpp:63] Initializing Beta Parameter from specified Beta = 0.01
W0109 07:09:19.219207 29329 Unigram_Model_Trainer.cpp:67] Beta param initialized
Outgoing.cpp:424: Ice::ObjectNotExistException:
object does not exist:
identity: `DM_Server_1'
facet: 
operation: ice_isA
terminate called after throwing an instance of 'IceUtil::Exception' what():  Outgoing.cpp:424: IceUtil::Exception
**\* Aborted at 1326121759 (unix time) try "date -d @1326121759" if you are using GNU date ***
PC: @       0x3354030265 (unknown)
**\* SIGABRT (@0xc3b800007291) received by PID 29329 (TID 0x2b661825a8e0) from PID 29329; stack trace: **\* @       0x335480eb10 (unknown) @       0x3354030265 (unknown) @       0x3354031d10 (unknown) @     0x2b6618015d14 (unknown) @     0x2b6618013e16 (unknown) @     0x2b6618013e43 (unknown) @     0x2b6618013f2a (unknown) @           0x43fa4e DM_Client::add_server() @           0x4403de DM_Client::DM_Client() @           0x49da45 Unigram_Model_Synchronizer_Helper::Unigram_Model_Synchronizer_Helper() @           0x49d465 Unigram_Model_Synchronized_Training_Builder::create_execution_strategy() @           0x447cb4 Model_Director::build_model() @           0x43965b main @       0x335401d994 (unknown) @           0x40d879 (unknown)
/data/2/mr/local/taskTracker/jwang/jobcache/job_201201082150_0047/attempt_201201082150_0047_m_000002_0/work/./LDA.sh: line 102: 29329 Aborted                 $LDALIBS/learntopics --model=$model --iter=$iters --topics=$topics --servers="$servers" --chkptdir="${MY_INP_DIR}" $flags 1>&2
Synch directory:  hdfs://hadooprsonn001.bo1.shopzilla.sea/user/jwang/workspace/ldanew/temporary/synchronize/learntopics
Num of map tasks:  20
Found 11 items
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:09 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/0
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:09 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/1
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/10
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/12
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/14
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/17
-rw-r--r--   3 mapred supergroup         10 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/18
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:09 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/2
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:09 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/3
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/5
-rw-r--r--   3 mapred supergroup          9 2012-01-09 07:08 /user/jwang/workspace/ldanew/temporary/synchronize/learntopics/9
Num of clients done:  9
Sleeping

**Comment by shravanmn** [comment]
Some servers have not started as indicated by

socket exception: Address already in use

I think thats because you are using 3144 as the max memory.

Currently, YLDA needs the entire machine for itself. This can be 
achieved only by setting the max memory to that allowed by your cluster. 
Otherwise, multiple instances of the process will be scheduled on the 
same machine which gives rise to the following error.

Open the job.xml of your previously failed job and check the value of 
_mapred.cluster.max.map.memory.mb_
and set the max mem parameter to this.

--Shravan

**Comment by josephykwang** [comment]
I'd pinged Cloudera about dynamic setting 1 mapper per node. Below is what they said:

As mentioned earlier, it's not possible to dynamically override 
mapreduce.tasktracker.map.tasks.maximum.  That value is only read once, 
when the task tracker daemon starts.  It is not possible to configure 
the number of map tasks per node within the job itself. 
If the task failure itself is causing issues, perhaps modifying the 
mapper to check a condition & exit gracefully if it finds another is already running will resolve the issue - for example, when it detects 
it can't bind to the socket?

I don't remember Yahoo! 3000-node mithril cluster is forcing 1-mapper per node. [BTW, I used to work at Y!.] How do you get around such issue?

thanks,

Joseph

**Comment by shravanmn** [comment]
I am not sure about the cloudera dist but the apache hadoop dist 
supports the mapred.job.{reduce|map}.memory.mb that can control how many 
reduce/map tasks run per node. This doesn't guarantee that only mappers 
or reducers will run exclusively though.

We have been running the same code on all grids without any problems.

--Shravan

josephykwang wrote:
